server:
    port: 28081
spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.105.98.68:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&characterSetResults=utf8&rewriteBatchedStatements=true&useSSL=false
        username: root
        password: NL@password123
